apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z4y4wrkpr-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6ad3a100134d5310a348bcc5c46e56c3077bfc0a@sha256:a9ac5d3864a363fb7d3d64818572ca5057c0364b252e0dbc47363e9eacf8a45c
          name: container-image
